package com.restaurant.ordering.service;
import com.restaurant.ordering.dto.*;
import com.restaurant.ordering.model.*;
import com.restaurant.ordering.repository.*;
import jakarta.transaction.Transactional;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.server.ResponseStatusException;
import java.math.BigDecimal;
import java.util.*;

@Service public class AdminService {
 private final RestaurantRepository restaurants; private final MenuItemRepository menuItems; private final EmployeeRepository employees; private final OrderRepository orders; private final DiningTableRepository diningTables; private final PaymentRepository payments; private final PasswordEncoder passwordEncoder;
 public AdminService(RestaurantRepository restaurants,MenuItemRepository menuItems,EmployeeRepository employees,OrderRepository orders,DiningTableRepository diningTables,PaymentRepository payments,PasswordEncoder passwordEncoder){this.restaurants=restaurants;this.menuItems=menuItems;this.employees=employees;this.orders=orders;this.diningTables=diningTables;this.payments=payments;this.passwordEncoder=passwordEncoder;}
 public List<MenuItem> menu(String slug){restaurant(slug);return menuItems.findByRestaurantSlugOrderByCategoryAscNameAsc(slug);}
 public List<Employee> employees(String slug){restaurant(slug);return employees.findByRestaurantSlugOrderByNameAsc(slug);}
 public List<Order> orders(String slug){restaurant(slug);return orders.findAllForRestaurant(slug);}
 public List<DiningTable> tables(String slug){restaurant(slug);return diningTables.findByRestaurantSlugOrderByTableNumberAsc(slug);}
 public List<DailySales> dailySales(String slug){restaurant(slug);Map<java.time.LocalDate,List<Payment>> grouped=payments.findByOrderRestaurantSlugOrderByPaidAtDesc(slug).stream().collect(java.util.stream.Collectors.groupingBy(p->p.getPaidAt().toLocalDate(),java.util.TreeMap::new,java.util.stream.Collectors.toList()));return grouped.entrySet().stream().sorted(Map.Entry.<java.time.LocalDate,List<Payment>>comparingByKey().reversed()).map(e->new DailySales(e.getKey(),e.getValue().size(),e.getValue().stream().map(Payment::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add))).toList();}
 @Transactional public MenuItem createMenuItem(String slug,MenuItemRequest r){Restaurant restaurant=restaurant(slug);validateMenu(r);return menuItems.save(new MenuItem(restaurant,r.name().trim(),nullable(r.description()),r.price(),r.category().trim(),nullable(r.emoji())));}
 @Transactional public MenuItem updateMenuItem(String slug,Long id,MenuItemRequest r){validateMenu(r);MenuItem item=menuItems.findByIdAndRestaurantSlug(id,slug).orElseThrow(()->notFound("Menu item"));item.update(r.name().trim(),nullable(r.description()),r.price(),r.category().trim(),nullable(r.emoji()),r.available());return item;}
 @Transactional public Employee createEmployee(String slug,EmployeeRequest r){Restaurant restaurant=restaurant(slug);validateEmployee(r);if(r.pin()==null||r.pin().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"A PIN is required for a new employee");return employees.save(new Employee(restaurant,r.name().trim(),r.role(),hash(r.pin())));}
 @Transactional public Employee updateEmployee(String slug,Long id,EmployeeRequest r){validateEmployee(r);Employee employee=employees.findByIdAndRestaurantSlug(id,slug).orElseThrow(()->notFound("Employee"));employee.update(r.name().trim(),r.role(),r.pin()==null||r.pin().isBlank()?null:hash(r.pin()));return employee;}
 @Transactional public DiningTable createTable(String slug,DiningTableRequest r){Restaurant restaurant=restaurant(slug);String number=tableNumber(r);if(diningTables.existsByRestaurantSlugAndTableNumber(slug,number))throw new ResponseStatusException(HttpStatus.CONFLICT,"That table already exists");DiningTable table=new DiningTable(restaurant,number);table.setActive(r.active());return diningTables.save(table);}
 @Transactional public DiningTable updateTable(String slug,Long id,DiningTableRequest r){DiningTable table=diningTables.findByIdAndRestaurantSlug(id,slug).orElseThrow(()->notFound("Table"));if(!table.getTableNumber().equals(tableNumber(r)))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Table numbers cannot be renamed; create a new table instead");table.setActive(r.active());return table;}
 public DashboardSummary summary(String slug){List<Order> all=orders(slug);long pending=all.stream().filter(o->o.getStatus()==Order.Status.PENDING||o.getStatus()==Order.Status.PREPARING).count();long ready=all.stream().filter(o->o.getStatus()==Order.Status.READY).count();List<Order> paid=all.stream().filter(o->o.getStatus()==Order.Status.PAID).toList();BigDecimal sales=paid.stream().map(Order::getTotal).reduce(BigDecimal.ZERO,BigDecimal::add);return new DashboardSummary(pending,ready,paid.size(),sales);}
 private Restaurant restaurant(String slug){return restaurants.findBySlug(slug).orElseThrow(()->notFound("Restaurant"));} private void validateMenu(MenuItemRequest r){if(r.name()==null||r.name().isBlank()||r.category()==null||r.category().isBlank()||r.price()==null||r.price().signum()<0)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Name, category, and a non-negative price are required");} private void validateEmployee(EmployeeRequest r){if(r.name()==null||r.name().isBlank()||r.role()==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Name and role are required");} private String tableNumber(DiningTableRequest r){if(r.tableNumber()==null||r.tableNumber().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Table number is required");return r.tableNumber().trim();} private String hash(String pin){return pin==null||pin.isBlank()?null:passwordEncoder.encode(pin);} private ResponseStatusException notFound(String type){return new ResponseStatusException(HttpStatus.NOT_FOUND,type+" not found");} private String nullable(String value){return value==null?null:value.trim();}
}
